- hosts: all
  vars:
    plugins_path: "/etc/amonagent/plugins/redisdb"
    enabled_plugins: "/etc/amonagent/plugins-enabled"
    name: "redisdb"
  # vars_prompt:
  # - name: "password"
  #   prompt: "Please enter your MongoDB connection string (Example: 127.0.0.1:27017/db)"
  tasks:
  - template: src={{ plugins_path }}/{{ name }}.conf.example dest={{ enabled_plugins }}/{{ name }}.conf
  - name: Install Plugin requirements
    pip: requirements={{ plugins_path }}/requirements.txt
  - name: Restart the agent
    command: /etc/init.d/amon-agent restart
  - name: Start redis 
    command: service redis-server start
  - name: Test the plugins
    command: /etc/init.d/amon-agent test_plugins