- hosts: localhost
  connection: local
  sudo: True
  vars:
    plugins_path: "/etc/amonagent/plugins/redisdb"
    enabled_plugins: "/etc/amonagent/plugins-enabled"
    name: "redisdb"
  vars_prompt:
  - name: "url"
    default: "redis://localhost:6379/0"
    prompt: "Please enter your Redis connection string:"
    private: no
  tasks:
  - template: src={{ plugins_path }}/{{ name }}.conf.example dest={{ enabled_plugins }}/{{ name }}.conf
  - name: Install Plugin requirements
    pip: requirements={{ plugins_path }}/requirements.txt
  - 
    service: name=amon-agent state=restarted
  - 
    service: name=redis-server state=started
    when: ansible_os_family == "Debian"
  - 
    service: name=redis state=started
    when: ansible_os_family == "RedHat"