- hosts: localhost
  connection: local
  vars:
    plugins_path: "/etc/amonagent/plugins/nginx"
    enabled_plugins: "/etc/amonagent/plugins-enabled"
    name: "nginx"
  tasks:
  - template: src={{ plugins_path }}/{{ name }}.conf.example dest={{ enabled_plugins }}/{{ name }}.conf
  - template: src={{ plugins_path }}/status_template dest=/etc/nginx/sites-enabled/amon
  - name: Restart nginx
    command: /etc/init.d/nginx restart
  - name: Test the plugins
    command: /etc/init.d/amon-agent test_plugins