- hosts: localhost
  connection: local
  sudo: True
  vars:
    plugins_path: "/etc/amonagent/plugins/mysql"
    enabled_plugins: "/etc/amonagent/plugins-enabled"
    name: "mysql"
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}"
    # database: "amon"
  vars_prompt:
  - name: "database"
    prompt: "Please select the MySQL database you wish to monitor"
    private: no
  tasks:
    - 
      name: Install python-devel
      yum: name=python-devel state=latest
      when: ansible_os_family == "RedHat"
    - 
      name: Install psycopg2
      yum: name=python-mysqldb
      when: ansible_os_family == "RedHat"
    - 
      name: Install python-dev
      apt: name=python-dev
      when: ansible_os_family == "Debian"
    - 
      name: Install psycopg2
      apt: name=python-mysqldb
      when: ansible_os_family == "Debian"
    - 
      template: src={{ plugins_path }}/{{ name }}.conf.example dest={{ enabled_plugins }}/{{ name }}.conf
    - 
      name: Start MySQL 
      command: service mysql start
    - 
      name: Add Amon user 
      sudo: True
      mysql_user: name=amon password={{ password }} priv=*.*:"REPLICATION CLIENT, SELECT" state=present
    - 
      name: Test the config file
      command: cat {{ enabled_plugins }}/{{ name }}.conf
    - 
      name: Test the plugins
      command: /etc/init.d/amon-agent test_plugins