- hosts: localhost
  connection: local
  sudo: True
  vars:
    plugins_path: "/etc/amonagent/plugins/postgres"
    enabled_plugins: "/etc/amonagent/plugins-enabled"
    name: "postgres"
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}"
    # database: "amon"
  vars_prompt:
  - name: "database"
    prompt: "Please select the PostgreSQL database you wish to monitor"
    private: no
  tasks:
    - 
      name: Install python-devel
      yum: name=python-devel state=latest
      when: ansible_os_family == "RedHat"
    - 
      name: Install psycopg2
      yum: name=python-psycopg2
      when: ansible_os_family == "RedHat"
    - 
      name: Install python-dev
      apt: name=python-dev
      when: ansible_os_family == "Debian"
    - 
      name: Install psycopg2
      apt: name=python-psycopg2
      when: ansible_os_family == "Debian"
    - 
      template: src={{ plugins_path }}/{{ name }}.conf.example dest={{ enabled_plugins }}/{{ name }}.conf
    - 
      name: Restart the agent
      command: /etc/init.d/amon-agent restart
    - 
      name: Start postgres 
      command: service postgresql start
    - 
      name: Create a database
      sudo: True
      sudo_user: postgres 
      postgresql_db: name=amon
    - 
      name: Add Amon user 
      sudo: True
      sudo_user: postgres 
      postgresql_user: name=amon db={{database}} password={{password}} priv=CONNECT
    - 
      name: Test the config file
      command: cat {{ enabled_plugins }}/{{ name }}.conf
    - 
       name: Grant SELECT privilegies
       sudo: True
       sudo_user: postgres
       postgresql_privs:
         database={{ database }}
         state=present
         objs=ALL_IN_SCHEMA
         privs=SELECT
         type=table
         roles=amon
         grant_option=yes
    - 
      name: Test the plugins
      command: /etc/init.d/amon-agent test_plugins